a = [1,2,7,8,99,100]
print("orginal",a)
a.append(50)
print("After append \'50\':", a)
a.sort()
print("After append and sorting: ",a)
a.reverse()
print("After Reverse: ",a)
a.insert(0, 1991)
print("After Insert \'1991\':", a)
